package mocks

import (
	"io"

	"github.com/compozed/deployadactyl/config"
	"github.com/compozed/deployadactyl/structs"
	"github.com/stretchr/testify/mock"
)

// BlueGreener is an autogenerated mock type for the BlueGreener type
type BlueGreener struct {
	mock.Mock
}

// Push provides a mock function with given fields: environment, appPath, deploymentInfo, out
func (_m *BlueGreener) Push(environment config.Environment, appPath string, deploymentInfo structs.DeploymentInfo, out io.Writer) error {
	ret := _m.Called(environment, appPath, deploymentInfo, out)

	var r0 error
	if rf, ok := ret.Get(0).(func(config.Environment, string, structs.DeploymentInfo, io.Writer) error); ok {
		r0 = rf(environment, appPath, deploymentInfo, out)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
