package mocks

import (
	"github.com/gin-gonic/gin"
	"github.com/stretchr/testify/mock"
)

// Endpoints is an autogenerated mock type for the Endpoints type
type Endpoints struct {
	mock.Mock
}

// Deploy provides a mock function with given fields: c
func (_m *Endpoints) Deploy(c *gin.Context) {
	_m.Called(c)
}
