package mocks

import "github.com/stretchr/testify/mock"

// Extractor is an autogenerated mock type for the Extractor type
type Extractor struct {
	mock.Mock
}

// Unzip provides a mock function with given fields: _a0, _a1, _a2
func (_m *Extractor) Unzip(_a0 string, _a1 string, _a2 string) error {
	ret := _m.Called(_a0, _a1, _a2)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, string) error); ok {
		r0 = rf(_a0, _a1, _a2)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
