package mocks

import "github.com/stretchr/testify/mock"

// Fetcher is an autogenerated mock type for the Fetcher type
type Fetcher struct {
	mock.Mock
}

// Fetch provides a mock function with given fields: url, manifest
func (_m *Fetcher) Fetch(url string, manifest string) (string, error) {
	ret := _m.Called(url, manifest)

	var r0 string
	if rf, ok := ret.Get(0).(func(string, string) string); ok {
		r0 = rf(url, manifest)
	} else {
		r0 = ret.Get(0).(string)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = rf(url, manifest)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
