package mocks

import (
	"github.com/compozed/deployadactyl/structs"
	"github.com/stretchr/testify/mock"
)

// Handler is an autogenerated mock type for the Handler type
type Handler struct {
	mock.Mock
}

// OnEvent provides a mock function with given fields: _a0
func (_m *Handler) OnEvent(_a0 structs.Event) error {
	ret := _m.Called(_a0)

	var r0 error
	if rf, ok := ret.Get(0).(func(structs.Event) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
