package mocks

import "github.com/compozed/deployadactyl/interfaces"
import "github.com/stretchr/testify/mock"

// PusherFactory is an autogenerated mock type for the PusherFactory type
type PusherFactory struct {
	mock.Mock
}

// CreatePusher provides a mock function with given fields:
func (_m *PusherFactory) CreatePusher() (interfaces.Pusher, error) {
	ret := _m.Called()

	var r0 interfaces.Pusher
	if rf, ok := ret.Get(0).(func() interfaces.Pusher); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(interfaces.Pusher)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
