package mocks

import "github.com/stretchr/testify/mock"

// Randomizer is an autogenerated mock type for the Randomizer type
type Randomizer struct {
	mock.Mock
}

// StringRunes provides a mock function with given fields: n
func (_m *Randomizer) StringRunes(n int) string {
	ret := _m.Called(n)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(n)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
