package mocks

import "github.com/stretchr/testify/mock"

// Rand is an autogenerated mock type for the Rand type
type Randomizer struct {
	mock.Mock
}

// StringRunes provides a mock function with given fields: _a0
func (_m *Randomizer) StringRunes(_a0 int) string {
	ret := _m.Called(_a0)

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
